export const REQUEST_TRANSACTION = "REQUEST_TRANSACTION";
export const RECEIVED_ALL_TRANSACTIONS = "RECEIVED_ALL_TRANSACTIONS";
export const RECEIVED_TRANSACTION_DETAIL = "RECEIVED_TRANSACTION_DETAIL";
export const ADD_ALERT = "ADD_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const ADD_NEW_TRANSACTION = "ADD_NEW_TRANSACTION";
